---
- hosts: Ubuntu
  become: True
  roles:
    - nagios

#- hosts: all
 # become: true
 # roles:
  #  - Elastic_Stack
  #  - kibana 
  #  - logstash

- hosts: all
  become: true
  roles:
    - prometheus
#    - influxdb
#    - grafana

- hosts: all
  become: true
  roles:
    - Lamp_Stack

